<?php

return [
    'name' => 'cbdas_landing',
    'title' => 'CBDAS Landing',
    'group' => 'IDASAN',
    'icon' => '${url:images/icon.svg}',
    'iconSmall' => '${url:images/iconSmall.svg}',
    'element' => true,
    'width' => 700,

    'templates' => [
        'render' => __DIR__ . '/templates/template.php',
        'content' => __DIR__ . '/templates/content.php',
    ],

    'defaults' => [
        'logo' => 'templates/yootheme_idasan/images/cbdas/logodark.webp',
        'hero_image' => 'templates/yootheme_idasan/images/cbdas/heroasset.png',
        'hero_background_image' => 'templates/yootheme_idasan/images/cbdas/elementosbrasilia2.png',
        'event_date' => '20 e 21 de agosto',
        'event_location' => 'Brasília - DF',
        'headline' => 'IIIº Congresso Brasileiro de Direito Administrativo Sancionador',
        'subtitle' => "Em Brasília de 20 a 21 de agosto de 2026\nIIIº Congresso Brasileiro de Direito Administrativo Sancionador",
        'primary_button_text' => 'Inscreva-se Agora',
        'primary_button_link' => 'https://www.eventweb.com.br/iii_cbdas/home-event/',
        'article_button_text' => 'Submissões de artigos',
        'article_button_link' => 'https://www.eventweb.com.br/iii_cbdas/home-event/',
        'instructions_button_text' => 'Instruções para submissão de artigo',
        'instructions_button_link' => 'https://drive.google.com/drive/u/0/folders/1lP3GMHOVfJF5ooIos8ABXinALEDs-bMv',
        'sponsor_button_text' => 'Seja um patrocinador',
        'sponsor_button_link' => 'https://docs.google.com/forms/d/e/1FAIpQLSczNtrBcQndorRXiGjOzr9X2pCgn4PlsxqT9zxMHquvpoaQHQ/viewform',
        'about_title' => 'IIIº CBDAS',
        'about_eyebrow' => 'Sobre o IIIº CBDAS',
        'about_text' => "O congresso brasileiro de direito administrativo sancionador chega à sua terceira edição consolidado como o principal fórum nacional dedicado ao estudo, debate e desenvolvimento do Direito Administrativo Sancionador.\n\nSediado desta vez em Brasília, o IIIº CBDAS reunirá especialistas, autoridades públicas, acadêmicos e profissionais de todas as regiões do país, promovendo o diálogo entre teoria, legislação e prática.\n\nO congresso reafirma seu compromisso com a diversidade regional, racial e de gênero, assegura pluralidade de perspectivas e fortalece o desenvolvimento institucional do Direito Administrativo Sancionador no Brasil.",
        'about_image_1' => 'templates/yootheme_idasan/images/cbdas/idasansampa.webp',
        'about_image_2' => 'templates/yootheme_idasan/images/cbdas/idasanpalcosampa.webp',
        'about_image_3' => 'templates/yootheme_idasan/images/cbdas/plateiaidasan.webp',
        'schedule_title' => 'Programação',
        'schedule_subtitle' => 'Agenda Completa',
        'schedule_items' => "Dia 1|08h30 - 09h00|Credenciamento|Atividade\nDia 1|09h00|Abertura|Cerimônia\nDia 1|09h30|Conferência de abertura|Conferência\nDia 1|10h - 11h15|Painel 1: Tribunais de Contas, medidas cautelares, dever de ressarcimento e sanções|Painel\nDia 1|11h15 - 12h30|Painel 2: DAS e a lei de inelegibilidade|Painel\nDia 1|14h15 - 15h30|Painel 3: Empresas estatais: nuances e questões polêmicas de DAS nos 10 anos de Estatuto|Painel\nDia 1|15h45 - 16h30|Painel 4: O conflito de interesses na administração pública: infração e julgamento|Painel\nDia 1|16h30 - 16h50|Coffee Break|Intervalo\nDia 1|17h00 - 17h30|IDASANcast: garantias no processo administrativo sancionador|Especial\nDia 1|17h30 - 18h30|Conferência especial: Reforma administrativa e responsabilização|Conferência\nDia 1|18h30 - 19h|Lançamentos|Cerimônia\nDia 2|9h - 10h15|Painel 5: O papel do DAS na regulação de serviços públicos e incentivo de conformidade|Painel\nDia 2|10h15 - 11h30|Painel 6: DAS na CVM e no Banco Central e o controle externo|Painel\nDia 2|11h30 - 12h30|CILADAS Credibilidade institucional e DAS|Especial\nDia 2|14h30 - 15h45|Painel 7: Governança e integridade pública|Painel\nDia 2|15h45 - 16h15|Prêmio IDASAN de Ouro ou Notáveis IDASAN Artigos científicos|Cerimônia\nDia 2|16h15 - 16h30|Coffee Break|Intervalo\nDia 2|16h30 - 17h|Conferência especial: Improbidade e DAS|Conferência\nDia 2|17h - 18h|Conferência de encerramento: Precisamos falar de uma lei geral de DAS?|Conferência",
        'speakers_title' => 'Palestrantes Confirmados',
        'speakers_text' => 'Especialistas, autoridades públicas, acadêmicos e profissionais reunidos para debater o Direito Administrativo Sancionador.',
        'speakers_items' => "Alice Voronoff|Vice-Presidente do IDASAN|templates/yootheme_idasan/images/cbdas/fotospalestrantes/alice voronoff.png\nAna Frazão|Professora Universidade de Brasília - UnB|templates/yootheme_idasan/images/cbdas/fotospalestrantes/draanafrazao.png\nFrancisco Zardo|Diretor Acadêmico do IDASAN|templates/yootheme_idasan/images/cbdas/fotospalestrantes/Francisco Zardo.png\nGustavo Henrique Justino de Oliveira|Prof. Doutor de Direito Administrativo - USP e IDP Brasília|templates/yootheme_idasan/images/cbdas/fotospalestrantes/06808AEB-A1E6-4E2C-9BE2-A24B66F88C27 - Gustavo Henrique Justino de Oliveira.jpeg\nJosé Guilherme Berman|Advogado e professor da PUC-Rio|templates/yootheme_idasan/images/cbdas/fotospalestrantes/joseguilhermeberman.png\nMichael de Jesus|Professor e pesquisador|templates/yootheme_idasan/images/cbdas/michaeldejesus.png",
        'articles_title' => 'Artigos Científicos',
        'articles_subtitle' => 'Submissão de trabalhos para o IIIº CBDAS',
        'articles_text' => 'Acesse a plataforma de submissões ou consulte as instruções completas para envio de artigos científicos ao IIIº Congresso Brasileiro de Direito Administrativo Sancionador.',
        'commitment_title' => 'Instruções para Empenho',
        'commitment_text' => "Razão Social|INSTITUTO DE DIREITO ADMINISTRATIVO SANCIONADOR BRASILEIRO - IDASAN\nCNPJ|39.963.974/0001-06\nSede|Rua Correia de Lemos, n° 645, unidade 43, São Paulo/SP, CEP 41.400-000\nDados Bancários|Banco Itaú, Agência 1664, Conta 99539-4",
        'commitment_docs_link' => 'https://drive.google.com/drive/folders/1x0YD9AyQhk0VHYiWMzZebGnGW8ZOy6bg?usp=sharing',
        'location_title' => 'Local do Evento',
        'location_name' => 'Centro Internacional de Convenções do Brasil (CICB)',
        'location_address' => 'SCES, Asa Sul Trecho 2 Conjunto 63 Lote 50 - Plano Piloto, Brasília - DF',
        'location_image' => 'templates/yootheme_idasan/images/cbdas/brasilia.jpeg',
        'maps_link' => 'https://maps.app.goo.gl/Sx1Rs9kcHU18QSbo9',
        'sponsors_title' => 'Patrocinadores e Apoiadores',
        'sponsor_diamond_image' => 'templates/yootheme_idasan/images/cbdas/Diamante.png',
        'sponsor_gold_image' => 'templates/yootheme_idasan/images/cbdas/Ouro.png',
        'sponsor_silver_image' => 'templates/yootheme_idasan/images/cbdas/Prata.png',
        'sponsor_supporters_image' => 'templates/yootheme_idasan/images/cbdas/apoiadores (2).png',
        'contact_title' => 'Contato',
        'contact_text' => 'O principal fórum nacional dedicado ao estudo, debate e desenvolvimento do Direito Administrativo Sancionador.',
        'contact_email' => 'contato@idasan.com.br',
        'instagram_link' => 'https://www.instagram.com/insta.idasan/',
        'linkedin_link' => 'https://www.linkedin.com/company/idasan/posts/?feedView=all&viewAsMember=true',
        'youtube_link' => 'https://www.youtube.com/@idasan9159',
        'footer_text' => '© 2026 IDASAN. Todos os direitos reservados.',
        'developer_logo' => 'templates/yootheme_idasan/images/cbdas/centoeonzelogo.png',
        'developer_link' => 'https://centoeonze.space/',
        'show_header' => true,
        'show_actions_band' => true,
        'show_speakers' => true,
        'show_sponsors' => true,
        'show_location' => true,
        'show_footer' => true,
    ],

    'fields' => [
        'logo' => ['label' => 'Logo', 'type' => 'image', 'source' => true],
        'hero_image' => ['label' => 'Arte/logo principal da hero', 'type' => 'image', 'source' => true],
        'hero_background_image' => ['label' => 'Imagem de fundo da hero', 'type' => 'image', 'source' => true],
        'event_date' => ['label' => 'Data do evento', 'source' => true],
        'event_location' => ['label' => 'Local do evento', 'source' => true],
        'headline' => ['label' => 'Título principal', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 2]],
        'subtitle' => ['label' => 'Subtítulo', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 3]],
        'primary_button_text' => ['label' => 'Texto do botão principal', 'source' => true],
        'primary_button_link' => ['label' => 'Link do botão principal', 'type' => 'link', 'source' => true],
        'article_button_text' => ['label' => 'Texto do botão artigos', 'source' => true],
        'article_button_link' => ['label' => 'Link do botão artigos', 'type' => 'link', 'source' => true],
        'instructions_button_text' => ['label' => 'Texto do botão instruções', 'source' => true],
        'instructions_button_link' => ['label' => 'Link do botão instruções', 'type' => 'link', 'source' => true],
        'sponsor_button_text' => ['label' => 'Texto do botão patrocinador', 'source' => true],
        'sponsor_button_link' => ['label' => 'Link do botão patrocinador', 'type' => 'link', 'source' => true],
        'about_eyebrow' => ['label' => 'Chamada da seção sobre', 'source' => true],
        'about_title' => ['label' => 'Título da seção sobre', 'source' => true],
        'about_text' => ['label' => 'Sobre o evento', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 8]],
        'about_image_1' => ['label' => 'Imagem sobre 1', 'type' => 'image', 'source' => true],
        'about_image_2' => ['label' => 'Imagem sobre 2', 'type' => 'image', 'source' => true],
        'about_image_3' => ['label' => 'Imagem sobre 3', 'type' => 'image', 'source' => true],
        'schedule_title' => ['label' => 'Título da programação', 'source' => true],
        'schedule_subtitle' => ['label' => 'Subtítulo da programação', 'source' => true],
        'schedule_items' => ['label' => 'Programação', 'description' => 'Uma atividade por linha: Dia|Horário|Título|Tipo', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 12]],
        'speakers_title' => ['label' => 'Título dos palestrantes', 'source' => true],
        'speakers_text' => ['label' => 'Texto dos palestrantes', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 3]],
        'speakers_items' => ['label' => 'Palestrantes', 'description' => 'Um palestrante por linha: Nome|Cargo|Imagem', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 8]],
        'articles_title' => ['label' => 'Título da seção artigos', 'source' => true],
        'articles_subtitle' => ['label' => 'Subtítulo da seção artigos', 'source' => true],
        'articles_text' => ['label' => 'Texto da seção artigos', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 4]],
        'commitment_title' => ['label' => 'Título da seção empenho', 'source' => true],
        'commitment_text' => ['label' => 'Dados de empenho', 'description' => 'Uma linha por dado: Rótulo|Valor', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 6]],
        'commitment_docs_link' => ['label' => 'Link dos documentos de empenho', 'type' => 'link', 'source' => true],
        'location_title' => ['label' => 'Título da seção local', 'source' => true],
        'location_name' => ['label' => 'Nome do local', 'source' => true],
        'location_address' => ['label' => 'Endereço', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 2]],
        'location_image' => ['label' => 'Imagem do local/Brasília', 'type' => 'image', 'source' => true],
        'maps_link' => ['label' => 'Link Como chegar', 'type' => 'link', 'source' => true],
        'sponsors_title' => ['label' => 'Título patrocinadores', 'source' => true],
        'sponsor_diamond_image' => ['label' => 'Imagem Diamante', 'type' => 'image', 'source' => true],
        'sponsor_gold_image' => ['label' => 'Imagem Ouro', 'type' => 'image', 'source' => true],
        'sponsor_silver_image' => ['label' => 'Imagem Prata', 'type' => 'image', 'source' => true],
        'sponsor_supporters_image' => ['label' => 'Imagem Apoiadores', 'type' => 'image', 'source' => true],
        'contact_title' => ['label' => 'Título da seção contato', 'source' => true],
        'contact_text' => ['label' => 'Texto do footer', 'type' => 'textarea', 'source' => true, 'attrs' => ['rows' => 3]],
        'contact_email' => ['label' => 'E-mail de contato', 'source' => true],
        'instagram_link' => ['label' => 'Instagram', 'type' => 'link', 'source' => true],
        'linkedin_link' => ['label' => 'LinkedIn', 'type' => 'link', 'source' => true],
        'youtube_link' => ['label' => 'YouTube', 'type' => 'link', 'source' => true],
        'footer_text' => ['label' => 'Texto final do footer', 'source' => true],
        'developer_logo' => ['label' => 'Logo do desenvolvedor', 'type' => 'image', 'source' => true],
        'developer_link' => ['label' => 'Link do desenvolvedor', 'type' => 'link', 'source' => true],
        'show_header' => ['label' => 'Exibir cabeçalho interno', 'type' => 'checkbox', 'text' => 'Mostrar navegação da landing'],
        'show_actions_band' => ['label' => 'Exibir faixa de acessos rápidos', 'type' => 'checkbox', 'text' => 'Mostrar botões abaixo da hero'],
        'show_speakers' => ['label' => 'Exibir palestrantes', 'type' => 'checkbox', 'text' => 'Mostrar seção de palestrantes'],
        'show_sponsors' => ['label' => 'Exibir patrocinadores', 'type' => 'checkbox', 'text' => 'Mostrar seção de patrocinadores'],
        'show_location' => ['label' => 'Exibir local', 'type' => 'checkbox', 'text' => 'Mostrar seção local'],
        'show_footer' => ['label' => 'Exibir footer', 'type' => 'checkbox', 'text' => 'Mostrar contato e rodapé'],
    ],

    'fieldset' => [
        'default' => [
            'type' => 'tabs',
            'fields' => [
                [
                    'title' => 'Hero',
                    'fields' => [
                        'logo',
                        'hero_image',
                        'hero_background_image',
                        'event_date',
                        'event_location',
                        'headline',
                        'subtitle',
                    ],
                ],
                [
                    'title' => 'Botões',
                    'fields' => [
                        'primary_button_text',
                        'primary_button_link',
                        'article_button_text',
                        'article_button_link',
                        'instructions_button_text',
                        'instructions_button_link',
                        'sponsor_button_text',
                        'sponsor_button_link',
                    ],
                ],
                [
                    'title' => 'Seções',
                    'fields' => [
                        'about_eyebrow',
                        'about_title',
                        'about_text',
                        'about_image_1',
                        'about_image_2',
                        'about_image_3',
                        'schedule_title',
                        'schedule_subtitle',
                        'schedule_items',
                        'speakers_title',
                        'speakers_text',
                        'speakers_items',
                        'articles_title',
                        'articles_subtitle',
                        'articles_text',
                        'commitment_title',
                        'commitment_text',
                        'commitment_docs_link',
                        'location_title',
                        'location_name',
                        'location_address',
                        'location_image',
                        'maps_link',
                        'sponsors_title',
                        'sponsor_diamond_image',
                        'sponsor_gold_image',
                        'sponsor_silver_image',
                        'sponsor_supporters_image',
                    ],
                ],
                [
                    'title' => 'Footer',
                    'fields' => [
                        'contact_title',
                        'contact_text',
                        'contact_email',
                        'instagram_link',
                        'linkedin_link',
                        'youtube_link',
                        'footer_text',
                        'developer_logo',
                        'developer_link',
                    ],
                ],
                [
                    'title' => 'Avançado',
                    'fields' => [
                        'show_header',
                        'show_actions_band',
                        'show_speakers',
                        'show_sponsors',
                        'show_location',
                        'show_footer',
                    ],
                ],
            ],
        ],
    ],
];
